<?php
/**
 * @file
 * Theme functions
 */

// Include all files from the includes directory.
$includes_path = dirname(__FILE__) . '/includes/*.inc';
foreach (glob($includes_path) as $filename) {
  require_once dirname(__FILE__) . '/includes/' . basename($filename);
}


/**
 * 
 * Implements hook_preprocess_HOOK()
 * Add class to atrributtes var
 */

function gmlifetheme_preprocess_paragraph__card_deck(&$variables) {

  $variables['atrributes']['class'][]= 'card-deck';

}